name: Repository Unit Test

on:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install package.json
        run: yarn

      - name: TS Type-Check
        run: yarn type-check

      - name: Run Lint
        run: yarn lint

      - name: Test Repository
        run: yarn test --silent=true
